project_id = "tqesyvmpdlbfmxfhdshb"

[functions.sitemap]
verify_jwt = false

[functions.robots]
verify_jwt = false

[functions.ai-support]
verify_jwt = false

[functions.bkash-create-payment]
verify_jwt = false

[functions.bkash-execute-payment]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
