-- Premium starter services for every existing service category.
-- Images are square-ready URLs and can be replaced later from the admin product editor.
insert into public.service_packages (
  service_id, title, slug, short_description, description, features,
  price, original_price, currency, image_url, is_published, is_featured,
  is_digital, sort_order
)
values
  ('9803acaa-10a4-4943-92b4-79f42c8214c3', 'Premium Corporate Website', 'premium-corporate-website', 'A high-impact corporate website with refined branding, lead generation, and conversion-ready content structure.', 'Position your company as an industry leader with a premium corporate website, strategic page architecture, responsive design, lead capture, portfolio presentation, and a polished brand experience.', array['Custom visual direction', 'Responsive page system', 'Lead-generation forms', 'Technical SEO foundation'], 45000, 55000, 'BDT', 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1080&h=1080&q=85', true, false, false, 100),
  ('9803acaa-10a4-4943-92b4-79f42c8214c3', 'Custom Web Application', 'custom-web-application', 'A tailored web application that turns complex workflows into fast, intuitive digital experiences.', 'From internal operations to customer-facing platforms, get a scalable web application with secure user flows, dashboards, integrations, and a product-focused interface.', array['Custom user journeys', 'Secure authentication', 'Role-based dashboards', 'API integration planning'], 85000, 100000, 'BDT', 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1080&h=1080&q=85', true, false, false, 101),
  ('bf163d61-ac1e-45fd-95bf-16539b0bf5d1', 'Performance Optimization', 'website-performance-optimization', 'A focused speed and stability upgrade for faster load times, smoother interactions, and better search performance.', 'Improve the experience of every visitor with performance diagnostics, asset optimization, responsive fixes, Core Web Vitals improvements, and practical technical recommendations.', array['Performance audit', 'Asset and image optimization', 'Core Web Vitals improvements', 'Technical recommendations'], 12000, 15000, 'BDT', 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1080&h=1080&q=85', true, false, false, 102),
  ('bf163d61-ac1e-45fd-95bf-16539b0bf5d1', 'Managed Website Support', 'managed-website-support', 'Ongoing technical support for updates, content changes, monitoring, and dependable day-to-day maintenance.', 'Keep your digital presence running with a reliable support partner for content updates, issue resolution, security checks, backups, and continuous technical assistance.', array['Priority support', 'Content and layout updates', 'Security checks', 'Backup monitoring'], 8000, 10000, 'BDT', 'https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=1080&h=1080&q=85', true, false, false, 103),
  ('0cae50dd-23d6-4c0b-b379-e8eb0951c2f2', 'Complete Brand Identity', 'complete-brand-identity', 'A cohesive visual identity system that makes your business recognizable, consistent, and ready to grow.', 'Create a confident brand presence with logo refinement, color and typography direction, stationery essentials, social assets, and a practical brand guideline system.', array['Logo direction', 'Color and typography system', 'Brand guideline document', 'Social media starter assets'], 28000, 35000, 'BDT', 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=1080&h=1080&q=85', true, false, false, 104),
  ('0cae50dd-23d6-4c0b-b379-e8eb0951c2f2', 'UI/UX Design System', 'ui-ux-design-system', 'A thoughtful interface design system that creates clarity, consistency, and confidence across every screen.', 'Design a polished product experience with user flows, wireframes, high-fidelity screens, reusable components, responsive states, and a scalable visual language.', array['User flow mapping', 'High-fidelity interface design', 'Reusable component library', 'Responsive screen states'], 38000, 48000, 'BDT', 'https://images.unsplash.com/photo-1559028012-481c04fa702d?auto=format&fit=crop&w=1080&h=1080&q=85', true, false, false, 105),
  ('56ac96ce-5893-42c5-8c3a-093a9584caf5', 'Technical SEO Audit', 'technical-seo-audit', 'A clear technical SEO audit that uncovers ranking barriers and turns them into an actionable growth plan.', 'Understand exactly what is limiting your visibility with a structured audit covering crawlability, indexing, performance, metadata, site structure, content signals, and priority fixes.', array['Technical audit report', 'Indexing and crawl review', 'Keyword and metadata review', 'Prioritized action plan'], 15000, 20000, 'BDT', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1080&h=1080&q=85', true, false, false, 106),
  ('56ac96ce-5893-42c5-8c3a-093a9584caf5', 'Content & Search Growth', 'content-search-growth', 'A content-led growth program built around search intent, authority, and qualified organic traffic.', 'Build long-term search visibility with content planning, topic research, on-page optimization, internal linking, and a publishing roadmap aligned with your business goals.', array['Content opportunity research', 'Topic and keyword mapping', 'On-page optimization', 'Publishing roadmap'], 22000, 28000, 'BDT', 'https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?auto=format&fit=crop&w=1080&h=1080&q=85', true, false, false, 107),
  ('8d9f031a-feb8-42f1-8582-f43dacaeb57f', 'Facebook Page Launch Kit', 'facebook-page-launch-kit', 'A polished Facebook presence with optimized branding, page setup, content direction, and launch-ready assets.', 'Set up your Facebook presence for trust and growth with profile optimization, branded visuals, page structure, call-to-action setup, and a clear launch checklist.', array['Page optimization', 'Branded cover and profile assets', 'CTA and contact setup', 'Launch checklist'], 9000, 12000, 'BDT', 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=1080&h=1080&q=85', true, false, false, 108),
  ('8d9f031a-feb8-42f1-8582-f43dacaeb57f', 'Social Campaign Accelerator', 'social-campaign-accelerator', 'A focused social campaign system combining creative direction, audience strategy, and measurable growth actions.', 'Move from random posting to a structured campaign with creative concepts, audience positioning, content themes, ad-ready assets, and performance checkpoints.', array['Campaign concept', 'Audience positioning', 'Creative direction', 'Performance checkpoints'], 18000, 24000, 'BDT', 'https://images.unsplash.com/photo-1611926653458-09294b3142bf?auto=format&fit=crop&w=1080&h=1080&q=85', true, false, false, 109),
  ('73d5cb49-c7d1-4d1c-bc77-1521fd3cd6ca', 'Business Email Setup', 'business-email-setup', 'Professional branded email setup that helps your team communicate with credibility and consistency.', 'Create a trustworthy business communication layer with branded email configuration, account setup guidance, DNS records, signatures, and practical team onboarding.', array['Branded email configuration', 'DNS setup guidance', 'Professional signatures', 'Team onboarding'], 6500, 8500, 'BDT', 'https://images.unsplash.com/photo-1557200134-90327ee9fafa?auto=format&fit=crop&w=1080&h=1080&q=85', true, false, false, 110),
  ('73d5cb49-c7d1-4d1c-bc77-1521fd3cd6ca', 'Digital Business Starter Kit', 'digital-business-starter-kit', 'A practical digital launch package combining domain, hosting, email, and the essentials for a credible online presence.', 'Start your business online with the essential infrastructure, guidance, and setup required to launch with confidence and maintain a professional digital presence.', array['Domain and hosting guidance', 'Business email setup', 'SSL and security basics', 'Launch checklist'], 18000, 23000, 'BDT', 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1080&h=1080&q=85', true, false, false, 111)
on conflict (slug) do nothing;
